import assert from "node:assert/strict";
import { describe, it } from "node:test";
import * as argon2 from "argon2";
import { JwtService } from "@nestjs/jwt";
import { AuthService } from "./auth.service";

// Generated by Bun.password.hash("legacy-password") using Bun 1.3.14.
const BUN_PASSWORD_HASH =
    "$argon2id$v=19$m=65536,t=2,p=1$5l4dusVWEcionsxc6mSlzgnvGBG2bPdvv2OIdHCgvRs$TREtIuxdcQFVPuGQ/kASbW8GCJ0zw54kGeScVLpo5OA";

describe("AuthService password compatibility", () => {
    it("verifies a password hash generated by Bun.password", async () => {
        assert.equal(await argon2.verify(BUN_PASSWORD_HASH, "legacy-password"), true);
        assert.equal(await argon2.verify(BUN_PASSWORD_HASH, "wrong-password"), false);
    });

    it("creates Bun-compatible Argon2id hashes for new passwords", async () => {
        let created: { email: string; passwordHash: string } | undefined;
        const users = {
            findOne: async () => null,
            create: async (record: { email: string; passwordHash: string }) => {
                created = record;
                return { ...record, _id: { toString: () => "user-id" } };
            },
        };
        const jwt = { signAsync: async () => "signed-token" };
        const service = new AuthService(users as never, jwt as never);

        const result = await service.register("reader@example.com", "a-good-password");

        assert.equal(result.token, "signed-token");
        assert.match(created!.passwordHash, /^\$argon2id\$v=19\$m=65536,(t=2,p=1|p=1,t=2)\$/);
        assert.equal(await argon2.verify(created!.passwordHash, "a-good-password"), true);
    });

    it("returns the same credential error for unknown users and incorrect passwords", async () => {
        const jwt = { signAsync: async () => "unused" };
        const missingUserService = new AuthService({ findOne: async () => null } as never, jwt as never);
        const wrongPasswordService = new AuthService(
            {
                findOne: async () => ({ email: "reader@example.com", passwordHash: BUN_PASSWORD_HASH }),
            } as never,
            jwt as never
        );

        await assert.rejects(missingUserService.login("missing@example.com", "password"), {
            response: { message: "Invalid credentials" },
        });
        await assert.rejects(wrongPasswordService.login("reader@example.com", "wrong-password"), {
            response: { message: "Invalid credentials" },
        });
    });

    it("signs tokens with the existing subject/email claims and configured lifetime", async () => {
        const users = {
            findOne: async () => null,
            create: async () => ({
                email: "reader@example.com",
                _id: { toString: () => "user-id" },
            }),
        };
        const jwt = new JwtService({ secret: "test-secret", signOptions: { expiresIn: 3600 } });
        const service = new AuthService(users as never, jwt);

        const { token } = await service.register("reader@example.com", "password");
        const payload = await jwt.verifyAsync<{ sub: string; email: string; iat: number; exp: number }>(token);

        assert.equal(payload.sub, "user-id");
        assert.equal(payload.email, "reader@example.com");
        assert.equal(payload.exp - payload.iat, 3600);
    });
});
